(cl:defpackage crazyflie_driver-srv
  (:use )
  (:export
   "SENDPACKET"
   "<SENDPACKET-REQUEST>"
   "SENDPACKET-REQUEST"
   "<SENDPACKET-RESPONSE>"
   "SENDPACKET-RESPONSE"
   "REMOVECRAZYFLIE"
   "<REMOVECRAZYFLIE-REQUEST>"
   "REMOVECRAZYFLIE-REQUEST"
   "<REMOVECRAZYFLIE-RESPONSE>"
   "REMOVECRAZYFLIE-RESPONSE"
   "UPDATEPARAMS"
   "<UPDATEPARAMS-REQUEST>"
   "UPDATEPARAMS-REQUEST"
   "<UPDATEPARAMS-RESPONSE>"
   "UPDATEPARAMS-RESPONSE"
   "ADDCRAZYFLIE"
   "<ADDCRAZYFLIE-REQUEST>"
   "ADDCRAZYFLIE-REQUEST"
   "<ADDCRAZYFLIE-RESPONSE>"
   "ADDCRAZYFLIE-RESPONSE"
  ))

